sudo: required
services:
  - docker

before_install:
  - docker build -t silima1/docker-react -f Dockerfile.dev .

script:
  - docker run silima1/docker-react npm run test -- --coverage

#@before_script:
  # Adicione essa etapa para instalar o @babel/preset-react antes de executar os testes
  #- docker exec -it silima1/docker-react npm install --save-dev @babel/preset-react
