sudo: required
services:
  - docker

before_install:
  - docker build -t silima1/docker-react -f Dockerfile.dev .
  - npm install -g create-react-app

script:
  - docker run silima1/docker-react npm install
  - docker run silima1/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-kubernet-env"
  bucket_name: "e-yqgz85amma"
  bucket_path: "Docker-kubernet"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

# Timeout personalizado
before_script:
  - echo "Setting a 30-minute timeout for the build"
  - date
  - export BUILD_TIMEOUT=1800  # 30 minutes in seconds
  - export BUILD_START_TIME=$(date +%s)

after_script:
  - export BUILD_END_TIME=$(date +%s)
  - export BUILD_DURATION=$((BUILD_END_TIME - BUILD_START_TIME))
  - echo "Build duration: $BUILD_DURATION seconds"
  - if [[ $BUILD_DURATION -ge $BUILD_TIMEOUT ]]; then echo "Build timed out!"; travis_terminate 1; fi
