sudo: required
services:
  - docker

before_install:
  - docker build -t silima1/docker-react -f Dockerfile.dev .
  - npm install -g create-react-app

script:
  - docker run silima1/docker-react npm install
  - docker run silima1/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-059532462828"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
