sudo: required
services:
  - docker

before_install:
  - docker build -t silima1/docker-react -f Dockerfile.dev .
  - npm install -g create-react-app

script:
  - docker run silima1/docker-react npm install
  - docker run silima1/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-kubernet-env"
  bucket_name: "e-yqgz85amma"
  bucket_path: "Docker-kubernet"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

# Adicione a seguinte seção para definir um timeout personalizado
addons:
  apt:
    packages:
      - timeout
  homebrew:
    packages:
      - timeout

# Script de timeout personalizado
after_script:
  - "timeout 1800 sleep 600"