# Use a imagem base do Node.js
FROM docker.io/library/node:alpine

# Defina o diretório de trabalho no contêiner
WORKDIR '/app'

# Copie o arquivo package.json e package-lock.json para o contêiner
COPY package.json package-lock.json ./

# Instale as dependências do projeto
RUN npm install

# Copie o restante dos arquivos do projeto para o contêiner
COPY . .

# Comando para iniciar a aplicação quando o contêiner for executado
CMD ["npm", "run", "start"]